### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/connect-four#1]
Change style of game to improve the gameplay

**Comment by hyperyuri** [comment]
Hey i`ll work on it

**Comment by eduqg** [comment]
Can I help too centralizing and changing a little bit the header? If its not a problem to @hyperyuri 

![Captura de tela de 2020-10-05 12-00-05](https://user-images.githubusercontent.com/17773211/95096206-59a13c00-0702-11eb-8b04-2211f7f9af4d.png)

**Comment by hyperyuri** [comment]
@eduqg yeahh! go ahead!

**Comment by hyperyuri** [comment]
@eduqg hey, look at my PR
<a href="https://github.com/vitobreda/connect-four/pull/2">link</a>
feel comfortable to change the header and related things
