### ISSUE TITLE
When someone wins, block game to not keeping playing

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/connect-four#4]
Implement a button to restart game when someone wins, and block to not keeping playing until hit restart button

**Comment by bruceyboy86** [comment]
I'll have a look

**Comment by Croustys** [comment]
I can fix that for you!

**Comment by meenahoda** [comment]
Hey, I've come up with a solution here: https://github.com/vitobreda/connect-four/pull/7 😄

**Comment by Croustys** [comment]
@vitobreda created a PR, when somebody wins the game, the game won't respond until it restarts. (auto restarts after 2.5s, can be changed by passing different parameter to the restart function). #8
