### ISSUE TITLE
Create redme

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/connect-four#5]
create a readme.md to explain how to start project and how it works.

**Comment by MarcelScherer** [comment]
Hello, ßI am a newcomer and was spurred on to join the "Hacktoberfest".  Can you explain what I shall do on this issue with more details

**Comment by mayank** [comment]
I will do this. Assign it to me.

**Comment by vitobreda** [comment]
> Hello, ßI am a newcomer and was spurred on to join the "Hacktoberfest". Can you explain what I shall do on this issue with more details

Hi, so i need a redme.md file to explain how this project work and what you need to do for starting the project, and if possivel some imagens

**Comment by mayank** [comment]
can you publish this on `Github Pages`.
